/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    views: [
        'Root'
    ],
    name: 'MyApp',

    launch: function() {

        Ext.create('MyApp.view.Root', { fullscreen: true });
        completedOnDropDownViewLoad(); // 드랍 다운 이벤트 관련 자바스크립트 dropDownEvents.js 정의 되어 있음
    }

});
